"""add away mode fields to businesses

Revision ID: 03d7e4281355
Revises: 38c869103e08
Create Date: 2026-09-01 16:41:23.300589

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d7e4281355'
down_revision: str | None = '38c869103e08'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'businesses',
        sa.Column('is_away', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column('businesses', sa.Column('away_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'away_message')
    op.drop_column('businesses', 'is_away')
    # ### end Alembic commands ###
