"""add user role

Revision ID: 12a118b65c12
Revises: 6e0c685780d2
Create Date: 2026-09-15 15:05:36.925575

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12a118b65c12"
down_revision: str | None = "6e0c685780d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


user_role_enum = sa.Enum("owner", "staff", name="user_role")


def upgrade() -> None:
    # Unlike op.create_table(), op.add_column() does NOT implicitly create the enum type first
    # (recurring gotcha, see every prior migration this session that added an enum column via
    # add_column rather than create_table).
    user_role_enum.create(op.get_bind(), checkfirst=True)
    # server_default added by hand (not autogenerated) — every existing user is, by definition,
    # the sole login on their business as of today, i.e. exactly the "owner" case.
    op.add_column(
        "users",
        sa.Column("role", user_role_enum, server_default=sa.text("'owner'"), nullable=False),
    )


def downgrade() -> None:
    op.drop_column("users", "role")
    # add_column's enum type isn't implicitly dropped by drop_column — must do it explicitly.
    user_role_enum.drop(op.get_bind(), checkfirst=True)
