"""add promotion type and active date range to knowledge_documents

Revision ID: 2a2e64e4b98f
Revises: 6073a3380f5b
Create Date: 2026-08-31 14:29:21.690481

Hand-written, not autogenerated: Alembic's autogenerate does not reliably detect a new value
added to an existing native Postgres enum type (knowledge_doc_type), so this adds it explicitly
via ALTER TYPE.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2e64e4b98f'
down_revision: str | None = '6073a3380f5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'knowledge_documents', sa.Column('active_from', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'knowledge_documents',
        sa.Column('active_until', sa.DateTime(timezone=True), nullable=True),
    )
    # Safe mid-transaction — nothing inserts type='promotion' in this same migration, and
    # ADD VALUE only fails inside a transaction if the new value is also *used* in it.
    op.execute("ALTER TYPE knowledge_doc_type ADD VALUE IF NOT EXISTS 'promotion'")

    # No RLS/GRANT changes needed — knowledge_documents is already covered at the table level
    # (325e6d70b285's _DIRECT_TABLES); a new column or enum value doesn't need new policy work.


def downgrade() -> None:
    op.drop_column('knowledge_documents', 'active_until')
    op.drop_column('knowledge_documents', 'active_from')

    # Postgres has no ALTER TYPE ... DROP VALUE. The standard workaround is to recreate the
    # type without 'promotion' and cast the column across — which FAILS if any row still has
    # type='promotion' (the cast has nothing valid to map it to). Deliberately not auto-deleting
    # those rows here — that would be silent data loss. Only verify this downgrade against a
    # database with no promotion rows present.
    op.execute("ALTER TYPE knowledge_doc_type RENAME TO knowledge_doc_type_old")
    op.execute("CREATE TYPE knowledge_doc_type AS ENUM ('product', 'policy', 'faq', 'brand_voice')")
    op.execute(
        "ALTER TABLE knowledge_documents ALTER COLUMN type TYPE knowledge_doc_type "
        "USING type::text::knowledge_doc_type"
    )
    op.execute("DROP TYPE knowledge_doc_type_old")
