"""add approval_requests table

Revision ID: 2f4a8bb3afd7
Revises: f41f529d1c21
Create Date: 2026-08-30 20:02:06.092577

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4a8bb3afd7'
down_revision: str | None = 'f41f529d1c21'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('drafted_reply', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('order_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_request_status'), nullable=False),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_requests_conversation_id', 'approval_requests', ['conversation_id'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: RLS (325e6d70b285's join-based pattern for messages/escalations —
    # approval_requests has no direct business_id column either, so the policy joins through
    # conversations, same as those two). Without this, reply_agent_app (the role
    # tenant_session.py uses for both the dashboard and the pipeline) has no access to this
    # table at all.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON approval_requests TO reply_agent_app")
    op.execute("ALTER TABLE approval_requests ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE approval_requests FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON approval_requests
        USING (
            EXISTS (
                SELECT 1 FROM conversations
                WHERE conversations.id = approval_requests.conversation_id
                AND conversations.business_id
                    = NULLIF(current_setting('app.current_business_id', true), '')::uuid
            )
        )
        WITH CHECK (
            EXISTS (
                SELECT 1 FROM conversations
                WHERE conversations.id = approval_requests.conversation_id
                AND conversations.business_id
                    = NULLIF(current_setting('app.current_business_id', true), '')::uuid
            )
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON approval_requests")
    op.execute("ALTER TABLE approval_requests NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE approval_requests DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON approval_requests FROM reply_agent_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approval_requests_conversation_id', table_name='approval_requests')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###

    # Not autogenerated: create_table's inline sa.Enum(...) implicitly creates the Postgres
    # ENUM type, but drop_table does not implicitly drop it back — found via a real
    # downgrade/upgrade round trip, which failed with "type already exists" on re-upgrade
    # without this.
    op.execute("DROP TYPE approval_request_status")
