"""add business requested whatsapp number

Revision ID: 3551c3bb2c64
Revises: 4c8463aff37f
Create Date: 2026-09-06 14:55:59.306685

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3551c3bb2c64"
down_revision: str | None = "4c8463aff37f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("requested_whatsapp_number", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "requested_whatsapp_number")
    # ### end Alembic commands ###
