"""add push_subscriptions table

Revision ID: 38c869103e08
Revises: 2a2e64e4b98f
Create Date: 2026-09-01 15:38:52.853845

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c869103e08'
down_revision: str | None = '2a2e64e4b98f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_subscriptions_endpoint')
    )
    op.create_index('ix_push_subscriptions_business_id', 'push_subscriptions', ['business_id'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: RLS (325e6d70b285's direct-business_id-column pattern, same shape as
    # approval_requests) — both the dashboard's push-subscribe/unsubscribe routes and the graph
    # pipeline's notification-sending code (notifications/push.py, called from escalate_to_owner
    # .py / request_owner_approval.py) go through tenant_session, which always connects as
    # reply_agent_app, not the superuser reply_agent role.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON push_subscriptions TO reply_agent_app")
    op.execute("ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE push_subscriptions FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON push_subscriptions
        USING (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        WITH CHECK (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON push_subscriptions")
    op.execute("ALTER TABLE push_subscriptions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE push_subscriptions DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON push_subscriptions FROM reply_agent_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_push_subscriptions_business_id', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
