"""add user accepted_terms_at

Revision ID: 45069662641c
Revises: d0ec71e17256
Create Date: 2026-09-01 19:59:12.406242

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45069662641c"
down_revision: str | None = "d0ec71e17256"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "accepted_terms_at")
    # ### end Alembic commands ###
