"""add order channel

Revision ID: 4c8463aff37f
Revises: fac8b73a084c
Create Date: 2026-09-06 14:13:07.747758

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c8463aff37f"
down_revision: str | None = "fac8b73a084c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column(
            "channel",
            sa.Enum("whatsapp", "instagram", "messenger", name="channel_type"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "channel")
    # ### end Alembic commands ###
