"""add estimated_window and sent_unchanged to approval_requests

Revision ID: 6073a3380f5b
Revises: 2f4a8bb3afd7
Create Date: 2026-08-31 13:35:30.525169

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6073a3380f5b'
down_revision: str | None = '2f4a8bb3afd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_requests', sa.Column('estimated_window', sa.Text(), nullable=True))
    op.add_column('approval_requests', sa.Column('sent_unchanged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('approval_requests', 'sent_unchanged')
    op.drop_column('approval_requests', 'estimated_window')
    # ### end Alembic commands ###
