"""initial schema

Revision ID: 6a30a431981d
Revises: 
Create Date: 2026-08-20 15:07:35.540949

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a30a431981d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channels_connected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_tier', sa.Enum('starter', 'growth', 'pro', name='plan_tier'), nullable=False),
    sa.Column('brand_voice_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'instagram', 'messenger', name='channel_type'), nullable=False),
    sa.Column('channel_handle', sa.Text(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_history_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'channel', 'channel_handle', name='uq_customer_identity')
    )
    op.create_index('ix_customers_business_id', 'customers', ['business_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('product', 'policy', 'faq', 'brand_voice', name='knowledge_doc_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_documents_business_id', 'knowledge_documents', ['business_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('starter', 'growth', 'pro', name='plan_tier'), nullable=False),
    sa.Column('message_usage_current_period', sa.Integer(), nullable=False),
    sa.Column('billing_status', sa.Enum('trialing', 'active', 'past_due', 'canceled', name='billing_status'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'instagram', 'messenger', name='channel_type'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('auto', 'owner_handled', 'closed', name='conversation_status'), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('ix_conversations_business_id', 'conversations', ['business_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('drafted_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'resolved', 'timed_out', name='escalation_status'), nullable=False),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('resolution_text', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_escalations_conversation_id', 'escalations', ['conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('inbound', 'outbound', name='message_direction'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent_label', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('channel_message_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_message_id', name='uq_messages_channel_message_id')
    )
    op.create_index('ix_messages_conversation_id', 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_escalations_conversation_id', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_conversations_business_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('subscriptions')
    op.drop_index('ix_knowledge_documents_business_id', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_customers_business_id', table_name='customers')
    op.drop_table('customers')
    op.drop_table('businesses')
    # ### end Alembic commands ###
