"""add product images

Revision ID: 6e0c685780d2
Revises: e8950a5db21d
Create Date: 2026-09-06 20:42:35.058444

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e0c685780d2"
down_revision: str | None = "e8950a5db21d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("image_data", sa.LargeBinary(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["knowledge_documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    # ### end Alembic commands ###

    # Not autogenerated: RLS, joined-table pattern (325e6d70b285's messages/escalations shape,
    # not the direct-business_id-column one) — product_images has no business_id of its own,
    # only document_id -> knowledge_documents.business_id. api/dashboard.py's product upload
    # routes write these through tenant_session, which always connects as reply_agent_app.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON product_images TO reply_agent_app")
    op.execute("ALTER TABLE product_images ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE product_images FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON product_images
        USING (
            EXISTS (
                SELECT 1 FROM knowledge_documents
                WHERE knowledge_documents.id = product_images.document_id
                AND knowledge_documents.business_id
                    = NULLIF(current_setting('app.current_business_id', true), '')::uuid
            )
        )
        WITH CHECK (
            EXISTS (
                SELECT 1 FROM knowledge_documents
                WHERE knowledge_documents.id = product_images.document_id
                AND knowledge_documents.business_id
                    = NULLIF(current_setting('app.current_business_id', true), '')::uuid
            )
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON product_images")
    op.execute("ALTER TABLE product_images NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE product_images DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON product_images FROM reply_agent_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_images")
    # ### end Alembic commands ###
