"""add orders table

Revision ID: 6e85f3c45e70
Revises: 688dae52fb69
Create Date: 2026-08-24 13:25:25.975596

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e85f3c45e70'
down_revision: str | None = '688dae52fb69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('order_reference', sa.Text(), nullable=False),
    sa.Column('customer_phone', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('items_summary', sa.Text(), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'order_reference', name='uq_order_reference')
    )
    op.create_index('ix_orders_business_id_customer_phone', 'orders', ['business_id', 'customer_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_business_id_customer_phone', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
