"""add order confirmation sent/nudge timestamps

Revision ID: 80994359e563
Revises: 06b374783401
Create Date: 2026-09-03 17:46:38.264023

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80994359e563'
down_revision: str | None = '06b374783401'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('confirmation_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('confirmation_nudge_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'confirmation_nudge_sent_at')
    op.drop_column('orders', 'confirmation_sent_at')
    # ### end Alembic commands ###
