"""add business agent enabled

Revision ID: 9e58b6f39182
Revises: 3551c3bb2c64
Create Date: 2026-09-06 15:02:31.827228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e58b6f39182"
down_revision: str | None = "3551c3bb2c64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (not autogenerated) — existing rows need a DB-level fill for
    # a NOT NULL column, same pattern as is_away's own original migration
    # (03d7e4281355_add_away_mode_fields_to_businesses.py). True: every existing business keeps
    # replying automatically exactly as before.
    op.add_column(
        "businesses",
        sa.Column("agent_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "agent_enabled")
    # ### end Alembic commands ###
