"""add custom_rules table

Revision ID: 9e7e58d38a35
Revises: 03d7e4281355
Create Date: 2026-09-01 17:09:12.415159

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7e58d38a35'
down_revision: str | None = '03d7e4281355'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('rule_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='custom_rule_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_custom_rules_business_id', 'custom_rules', ['business_id'], unique=False)
    # ### end Alembic commands ###

    # Not autogenerated: RLS (325e6d70b285's direct-business_id-column pattern, same shape as
    # push_subscriptions) — the dashboard's rules routes and generate_response.py's approved-
    # rule lookup both go through tenant_session, which always connects as reply_agent_app.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON custom_rules TO reply_agent_app")
    op.execute("ALTER TABLE custom_rules ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE custom_rules FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON custom_rules
        USING (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        WITH CHECK (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON custom_rules")
    op.execute("ALTER TABLE custom_rules NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE custom_rules DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON custom_rules FROM reply_agent_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_rules_business_id', table_name='custom_rules')
    op.drop_table('custom_rules')
    # ### end Alembic commands ###

    # Not autogenerated: create_table's inline sa.Enum(...) implicitly creates the Postgres
    # ENUM type, but drop_table does not implicitly drop it back (the same gotcha found while
    # building approval_requests's migration earlier this session).
    op.execute("DROP TYPE custom_rule_status")
