"""add api call log

Revision ID: e8950a5db21d
Revises: 9e58b6f39182
Create Date: 2026-09-06 19:57:08.538241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8950a5db21d"
down_revision: str | None = "9e58b6f39182"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_call_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("business_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.Text(), nullable=False),
        sa.Column("node_name", sa.Text(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("anthropic", "google_maps", "voyage", name="api_call_provider"),
            nullable=False,
        ),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=14, scale=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["business_id"], ["businesses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_api_call_logs_business_id_thread_id",
        "api_call_logs",
        ["business_id", "thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Not autogenerated: RLS (325e6d70b285's direct-business_id-column pattern, same shape as
    # custom_rules/push_subscriptions) — every graph node writes ApiCallLog rows through
    # tenant_session, which always connects as reply_agent_app, never the superuser role.
    # Caught by a real test run locally (permission denied for table api_call_logs) before
    # this was ever pushed anywhere.
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON api_call_logs TO reply_agent_app")
    op.execute("ALTER TABLE api_call_logs ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE api_call_logs FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON api_call_logs
        USING (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        WITH CHECK (
            business_id = NULLIF(current_setting('app.current_business_id', true), '')::uuid
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON api_call_logs")
    op.execute("ALTER TABLE api_call_logs NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE api_call_logs DISABLE ROW LEVEL SECURITY")
    op.execute("REVOKE ALL ON api_call_logs FROM reply_agent_app")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_api_call_logs_business_id_thread_id", table_name="api_call_logs")
    op.drop_table("api_call_logs")
    # ### end Alembic commands ###

    # Not autogenerated — create_table's inline sa.Enum(...) creates the Postgres type on
    # upgrade, but drop_table does NOT drop it back on downgrade, so a second upgrade would
    # fail with "type already exists" without this (verified via a real round trip locally,
    # same gotcha custom_rules's own migration already hit).
    op.execute("DROP TYPE api_call_provider")
