"""add delivery estimation fields to businesses and orders

Revision ID: f41f529d1c21
Revises: 325e6d70b285
Create Date: 2026-08-28 16:49:28.530015

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f41f529d1c21'
down_revision: str | None = '325e6d70b285'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('address', sa.Text(), nullable=True))
    op.add_column(
        'businesses',
        sa.Column(
            'delivery_rules',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column('orders', sa.Column('delivery_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_window_promised', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('delivery_status', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_status')
    op.drop_column('orders', 'delivery_window_promised')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('businesses', 'delivery_rules')
    op.drop_column('businesses', 'address')
    # ### end Alembic commands ###
