"""add business facebook_user_id

Revision ID: fac8b73a084c
Revises: 80994359e563
Create Date: 2026-09-04 17:55:49.170395

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fac8b73a084c"
down_revision: str | None = "80994359e563"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("businesses", sa.Column("facebook_user_id", sa.Text(), nullable=True))
    op.create_index(
        "ix_businesses_facebook_user_id", "businesses", ["facebook_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_businesses_facebook_user_id", table_name="businesses")
    op.drop_column("businesses", "facebook_user_id")
    # ### end Alembic commands ###
